{% set name = "gguf" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gguf-{{ version }}.tar.gz
  sha256: f5e70987e15b19c545f6a9f7533b4033fb306330eb1f3c5c95fd28b14c3fd33b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - gguf-convert-endian = "scripts:gguf_convert_endian_entrypoint"
    - gguf-dump = "scripts:gguf_dump_entrypoint"
    - gguf-set-metadata = "scripts:gguf_set_metadata_entrypoint"

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
  run:
    - python >=3.8
    - numpy >=1.17

test:
  imports:
    - gguf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ggml.ai
  summary: Read and write ML models in GGUF for GGML
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
