context:
  name: gguf
  version: 0.10.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/gguf-${{ version }}.tar.gz
  sha256: 52a30ef26328b419ffc47d9269fc580c238edf1c8a19b5ea143c323e04a038c1

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  number: 0
  python:
    entry_points:
      - gguf-convert-endian = "scripts:gguf_convert_endian_entrypoint"
      - gguf-dump = "scripts:gguf_dump_entrypoint"
      - gguf-set-metadata = "scripts:gguf_set_metadata_entrypoint"

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
  run:
    - python >=3.8
    - numpy >=1.17

tests:
  - python:
      imports:
        - gguf

about:
  homepage: https://ggml.ai
  summary: Read and write ML models in GGUF for GGML
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sodre
    - wolfv
